branches:
  only:
  - develop
language: php
php:
- 5.4
- 5.5
- 5.6
sudo: false
before_script:
- composer install
script: vendor/bin/phpunit
deploy:
  provider: codedeploy
  access_key_id: AKIAICX4EQAQ2SP3PGGA
  secret_access_key: &1
    secure: Lfj+Y25NM1648z/tPtkG45BDDGPbZU6ecgyou1P7fkDjy1CPxUO5mwlFtevEsb4SuAZx9XVmfqdRK496R5Pnvw93B916xYKhsD8WduerMAw4mLv1HuBwZ8ZciFEQTA4PY75IU59YeLkBrTCp8bBT2pyi+oh2BG0pc2He8jKuHjs=
  bucket: "comicclouddeploy"
  key: latest/MyApp.zip
  application: TestComicCloud
  deployment_group: TestComicCloudDeploymentGroup
  on:
    branch: develop