branches:
  only:
  - develop
language: php
php:
- 5.4
- 5.5
- 5.6
sudo: false
before_script:
- composer install
script: vendor/bin/phpunit
deploy:
- provider: s3
  access_key_id: AKIAICX4EQAQ2SP3PGGA
  secret_access_key: &1
    secure: n9GIsu4WK7YiwdnZcfKpGQH+rrdV42n7FWJT1dF6oPRUO1bUKgsAYPMh0M5S4wA4A//QzA0iS7uE7/rVSPUyZmX7A8KtQOeLHkJL4tO5IZMMsRrBJFncOBFJVagoB764QrTjKd+mC113LXMJec9zhwr+aOHeTD/MzlFhKAPaS8g=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: kidshenlong/Comic-Cloud-API
    branch: develop
  bucket: comicclouddeploy
  upload_dir: latest
- provider: codedeploy
  access_key_id: AKIAICX4EQAQ2SP3PGGA
  secret_access_key: *1
  bucket: comicclouddeploy
  key: latest/Comic-Cloud-API.zip
  bundle_type: zip
  application: TestComicCloud
  deployment_group: TestComicCloudDeploymentGroup
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv Comic-Cloud-API.zip dpl_cd_upload/Comic-Cloud-API.zip
