branches:
  only:
  - develop
language: php
php:
- 5.4
- 5.5
- 5.6
sudo: false
before_script:
- composer install
script: vendor/bin/phpunit
deploy:
- provider: codedeploy
  revision_type: github
  application: TestComicCloud
  deployment_group: TestComicCloudDeploymentGroup
  on:
    repo: kidshenlong/Comic-Cloud-API
    branch: develop